### ISSUE TITLE
conda Issue

### ISSUE THREAD

**Issue by johnduenas15** [amichuda/Experimetrics-BITSS-Workshop#1]
Hi!

I'm having an issue with the previous step to install the Stata Kernel

![image](https://user-images.githubusercontent.com/46244244/50784433-987b3700-127b-11e9-8434-ebc85b7b2139.png)

Anyone is having the same problem?
Thanks for the help!

John

**Comment by lordflaron** [comment]
Thanks for posting!

Can you try typing this in the anaconda prompt:

conda --help

To check if you conda command line. Then try

pip --help

(Each with a space in between)
Do you get output from the pip command ? If so then you can skip that step. If not let me know. 

Also, can you rewrite this problem as an issue on the GitHub, so other people can also check if they have a problem?

**Comment by lordflaron** [comment]
Great! I've changed the readme file to reflect that.
